#pragma once
#define SDL_MAIN_HANDLED
//Board
#define BOARD_RENDERER_COL 12
#define BOARD_RENDERER_ROW 22
#define BOARD_HEIGHT 20
#define BOARD_WIDTH 10
#define BOARD_X 0
#define BOARD_Y 0
#define SIZE_CELL 30

//Window
#define WINDOW_WIDTH (BOARD_RENDERER_COL * SIZE_CELL * 2)
#define WINDOW_HEIGHT (BOARD_RENDERER_ROW * SIZE_CELL)

//SHAPE
#define SHAPE_MATRIX_SIZE 4
#define SHAPE_START_X 1
#define SHAPE_START_Y 4

//
#define SIZE_TEXT 32
#define SIZE_NUMBER 15

#define X_SCORE_BOARD (15 * SIZE_CELL)
#define Y_SCORE_BOARD (2 * SIZE_CELL)
#define SCORE_BOARD_HEIGHT (5 * SIZE_CELL)
#define SCORE_BOARD_WIDTH (6 * SIZE_CELL)

#define X_SCORE_TEXT (X_SCORE_BOARD + SIZE_CELL) 
#define Y_SCORE_TEXT Y_SCORE_BOARD
#define SCORE_TEXT_HEIGHT SIZE_CELL
#define SCORE_TEXT_WIDTH (SCORE_BOARD_WIDTH - 2 * SIZE_CELL)

#define X_SCORE (X_SCORE_BOARD + SIZE_CELL) 
#define Y_SCORE (Y_SCORE_BOARD + 2 * SIZE_CELL)
#define SCORE_HEIGHT SIZE_CELL
#define SCORE_WIDTH (SCORE_BOARD_WIDTH - 2 * SIZE_CELL)

#define X_NEXT_SHAPE_BOARD (X_SCORE_BOARD - SIZE_CELL)
#define Y_NEXT_SHAPE_BOARD (11 * SIZE_CELL)
#define NEXT_SHAPE_BOARD_HEIGHT (8 * SIZE_CELL)
#define NEXT_SHAPE_BOARD_WIDTH (8 * SIZE_CELL)

#define X_NEXT_SHAPE_TEXT (X_NEXT_SHAPE_BOARD + SIZE_CELL)
#define Y_NEXT_SHAPE_TEXT Y_NEXT_SHAPE_BOARD
#define NEXT_SHAPE_TEXT_HEIGHT SIZE_CELL
#define NEXT_SHAPE_TEXT_WIDTH (NEXT_SHAPE_BOARD_WIDTH - 2 * SIZE_CELL)

#define X_NEXT_SHAPE (X_NEXT_SHAPE_BOARD + 3 * SIZE_CELL)
#define Y_NEXT_SHAPE (Y_NEXT_SHAPE_BOARD + 2 * SIZE_CELL)

