#pragma once
#define SDL_MAIN_HANDLED
#define BOARD_RENDERER_COL 12
#define BOARD_RENDERER_ROW 22
#define BOARD_HEIGHT 20
#define BOARD_WIDTH 10
#define SIZE_CELL 30
#define WINDOW_WIDTH (BOARD_RENDERER_COL * SIZE_CELL)
#define WINDOW_HEIGHT (BOARD_RENDERER_ROW * SIZE_CELL)
#define SIZE_SHAPE 4
#define START_X 1
#define START_Y 4