#pragma once
#define SDL_MAIN_HANDLED

////Game definition for Window

//Board
#define BOARD_RENDERER_COL 12
#define BOARD_RENDERER_ROW 22
#define BOARD_HEIGHT 20
#define BOARD_WIDTH 10
#define WALL_SIZE 1
#define BOARD_X 0
#define BOARD_Y 0
#define SIZE_CELL 30


//Window
#define WINDOW_WIDTH (BOARD_RENDERER_COL * SIZE_CELL * 2)
#define WINDOW_HEIGHT (BOARD_RENDERER_ROW * SIZE_CELL)

//SHAPE
#define SHAPE_MATRIX_SIZE 4
#define SHAPE_START_X 1
#define SHAPE_START_Y 4

//Text
#define TEXT_SIZE 32
#define SIZE_NUMBER 24

//Score Board
#define X_SCORE_BOARD (15 * SIZE_CELL)
#define Y_SCORE_BOARD (2 * SIZE_CELL)
#define SCORE_BOARD_HEIGHT (5 * SIZE_CELL)
#define SCORE_BOARD_WIDTH (6 * SIZE_CELL)

#define SCORE_TEXT_HEIGHT SIZE_CELL
#define SCORE_TEXT_WIDTH (SCORE_BOARD_WIDTH - 2 * SIZE_CELL)
#define X_SCORE_TEXT (X_SCORE_BOARD + (SCORE_BOARD_WIDTH - SCORE_TEXT_WIDTH) / 2) 
#define Y_SCORE_TEXT (Y_SCORE_BOARD - SIZE_CELL)

#define SCORE_HEIGHT SIZE_CELL
#define SCORE_WIDTH (SCORE_BOARD_WIDTH - 2 * SIZE_CELL)
#define X_SCORE (X_SCORE_BOARD + (SCORE_BOARD_WIDTH - SCORE_WIDTH) / 2 )
#define Y_SCORE (Y_SCORE_BOARD + (SCORE_BOARD_HEIGHT - SCORE_HEIGHT) / 2 )

//Next shape board
#define X_NEXT_SHAPE_BOARD (X_SCORE_BOARD - SIZE_CELL)
#define Y_NEXT_SHAPE_BOARD (11 * SIZE_CELL)
#define NEXT_SHAPE_BOARD_HEIGHT (8 * SIZE_CELL)
#define NEXT_SHAPE_BOARD_WIDTH (8 * SIZE_CELL)

#define NEXT_SHAPE_TEXT_HEIGHT SIZE_CELL
#define NEXT_SHAPE_TEXT_WIDTH (NEXT_SHAPE_BOARD_WIDTH - 2 * SIZE_CELL)
#define X_NEXT_SHAPE_TEXT (X_NEXT_SHAPE_BOARD + (NEXT_SHAPE_BOARD_WIDTH - NEXT_SHAPE_TEXT_WIDTH) / 2)
#define Y_NEXT_SHAPE_TEXT (Y_NEXT_SHAPE_BOARD - SIZE_CELL)
#define NEXT_SHAPE_SCALE 1

#define GAME_OVER_POPUP_WIDTH 7
#define GAME_OVER_POPUP_HEIGHT 5

//Text
#define TEXT_GAME_OVER_WIDTH 5
#define TEXT_GAME_OVER_HEIGHT 1

#define TEXT_GAME_RESULT_WIDTH 2
#define TEXT_GAME_RESULT_HEIGHT 1


#define TEXT_PLAY_AGAIN_WIDTH 3
#define TEXT_PLAY_AGAIN_HEIGHT 1


#define YES_BUTTON_WIDTH 1
#define YES_BUTTON_HEIGHT 1


#define NO_BUTTON_WIDTH 1
#define NO_BUTTON_HEIGHT 1

//Game definition for android
#ifdef __ANDROID__

//Score board
#define X_SCORE_BOARD (SIZE_CELL / 2)
#define Y_SCORE_BOARD ((BOARD_RENDERER_ROW + 2) * SIZE_CELL)
#define SCORE_BOARD_HEIGHT (5 * SIZE_CELL)
#define SCORE_BOARD_WIDTH (5 * SIZE_CELL)

//Next shape board
#define X_NEXT_SHAPE_BOARD (X_SCORE_BOARD + 6 * SIZE_CELL)
#define Y_NEXT_SHAPE_BOARD (Y_SCORE_BOARD)
#define NEXT_SHAPE_BOARD_HEIGHT (5 * SIZE_CELL)
#define NEXT_SHAPE_BOARD_WIDTH (5 * SIZE_CELL)

#define NEXT_SHAPE_SCALE 0.5
//Window
#define WINDOW_WIDTH (BOARD_RENDERER_COL * SIZE_CELL)
#define WINDOW_HEIGHT ((BOARD_RENDERER_ROW + 3)  * SIZE_CELL + SCORE_BOARD_HEIGHT)
#endif